server:
  port: 8081
spring:
  datasource:
    username: alexjmatos
    password: alexjmatos6323
    url: jdbc:postgresql://localhost:5432/timesheet-microservice-db
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  jackson:
    default-property-inclusion: non_null